#!/usr/bin/env python3

# botchat_to_chat_js.py
# Description: Converts a specially formatted MD file (with timed chat messages, questions, and comments)
#              into a JavaScript array of message action objects for the live shopping app's chat feature,
#              reusing original bot naming conventions.
# Requirement: None (uses standard Python libraries)

import re
import json
import os

def mm_ss_to_seconds(time_str):
    """Converts (MM:SS) or MM:SS string to total seconds."""
    match = re.match(r'\(?(\d{2}):(\d{2})\)?', time_str)
    if match:
        minutes = int(match.group(1))
        seconds = int(match.group(2))
        return (minutes * 60) + seconds
    return 0

def convert_botchat_to_js_v3(md_file_path, output_js_file_path, default_channel_name="game.chat"):
    """
    Parses an MD file with timed chat messages and writes the data to a JavaScript
    file containing an array of message action objects, using original bot naming conventions.

    Args:
        md_file_path (str): Path to the input MD file.
        output_js_file_path (str): Path for the output JavaScript file.
        default_channel_name (str): The default PubNub channel name for the chat actions.
    """
    message_actions = []
    # Use a list of bot names matching the original app's convention (e.g., bot-01 to bot-40)
    original_bot_users = [f"bot-{i:02d}" for i in range(1, 41)] 
    current_bot_idx = 0

    line_regex = re.compile(r'^\((\d{2}:\d{2})\)\s*(?:(Question|Comment):\s*)?(.*)')

    try:
        with open(md_file_path, 'r', encoding='utf-8') as f_in:
            for line in f_in:
                line = line.strip()
                if not line or line.startswith('#') or line.startswith('---') or line.startswith('(Ambient Approx.'):
                    continue

                match = line_regex.match(line)
                if match:
                    time_str = match.group(1)
                    # msg_type (Question/Comment) is parsed but not used for user differentiation anymore
                    # All messages will cycle through the original_bot_users pool.
                    msg_type = match.group(2) 
                    message_content = match.group(3).strip()

                    if message_content.startswith('"') and message_content.endswith('"'):
                        message_content = message_content[1:-1]
                    
                    time_in_seconds = mm_ss_to_seconds(time_str)
                    time_in_ms = time_in_seconds * 1000
                    
                    # Cycle through the original bot user pool for all messages
                    user = original_bot_users[current_bot_idx]
                    current_bot_idx = (current_bot_idx + 1) % len(original_bot_users)
                    
                    message_actions.append({
                        "timeSinceVideoStartedInMs": time_in_ms,
                        "persistInHistory": False, 
                        "action": {
                            "channel": default_channel_name,
                            "data": {
                                "user": user,
                                "text": message_content
                            }
                        }
                    })
                else:
                    if line: 
                        print(f"Warning: Could not parse line: {line}")
                        
    except FileNotFoundError:
        print(f"Error: Input MD file not found at {md_file_path}")
        return
    except Exception as e:
        print(f"An error occurred during MD parsing: {e}")
        return

    message_actions.sort(key=lambda x: x['timeSinceVideoStartedInMs'])

    try:
        with open(output_js_file_path, 'w', encoding='utf-8') as f_out:
            f_out.write(f"// Generated by botchat_to_chat_js.py from {os.path.basename(md_file_path)}\n")
            f_out.write(f"// Target structure: Array of message action objects using original bot names\n\n")
            f_out.write("export const generatedChatActions = [\n") 
            for i, action_data in enumerate(message_actions):
                f_out.write("  {\n")
                f_out.write(f"    timeSinceVideoStartedInMs: {action_data['timeSinceVideoStartedInMs']},\n")
                f_out.write(f"    persistInHistory: {str(action_data['persistInHistory']).lower()},\n")
                f_out.write("    action: {\n")
                f_out.write(f"      channel: '{action_data['action']['channel']}',\n")
                f_out.write("      data: {\n")
                f_out.write(f"        user: '{action_data['action']['data']['user']}',\n")
                js_text = action_data['action']['data']['text'].replace('\\','\\\\').replace("'","\\'").replace('"','\\"')
                f_out.write(f"        text: '{js_text}'\n")
                f_out.write("      }\n")
                f_out.write("    }\n")    
                f_out.write(f"  }}{',' if i < len(message_actions) - 1 else ''}\n")
            f_out.write("];\n")
        print(f"Successfully converted {md_file_path} to {output_js_file_path} with original bot name structure.")
        print(f"Total message actions processed: {len(message_actions)}")
    except Exception as e:
        print(f"An error occurred during JS writing: {e}")

if __name__ == '__main__':
    script_dir = os.path.dirname(__file__) if '__file__' in locals() else os.getcwd()
    md_file = os.path.join(script_dir, 'botChat.md')
    # Output filename remains the same, as this version supersedes the previous one with the correct user naming.
    output_js_file = os.path.join(script_dir, 'generated_chat_actions.js') 
    # Use the original channel name for chat
    chat_channel = "game.chat"

    print(f"Attempting to convert '{md_file}' to '{output_js_file}' with original bot name structure...")
    convert_botchat_to_js_v3(md_file, output_js_file, chat_channel) 