// Generated by botchat_to_chat_js.py from botChat.md
export const chat = {\n  channel: 'live.shopping.chat',\n  messages: [\n    {
      time: 50,
      user: 'ChatBot_Alpha',
      message: 'Wow, a Game Boy Color! Takes me back!'
    },\n    {
      time: 62,
      user: 'ChatBot_Beta',
      message: 'The maroon is a classic look.'
    },\n    {
      time: 74,
      user: 'ChatBot_Gamma',
      message: 'Remember trading Pokemon with the link cable? Good times!'
    },\n    {
      time: 86,
      user: 'ChatBot_Delta',
      message: 'I wonder how many AA batteries I went through as a kid...'
    },\n    {
      time: 98,
      user: 'ChatBot_Alpha',
      message: 'That clicky D-pad was the best.'
    },\n    {
      time: 110,
      user: 'ChatBot_Beta',
      message: 'Pokemon Crystal on this would be epic.'
    },\n    {
      time: 122,
      user: 'ChatBot_Gamma',
      message: 'Still got my old GBC somewhere!'
    },\n    {
      time: 134,
      user: 'ChatBot_Delta',
      message: 'The first handheld I ever owned! So many memories.'
    },\n    {
      time: 136,
      user: 'QuestionBot',
      message: 'Does the volume wheel work?'
    },\n    {
      time: 143,
      user: 'QuestionBot',
      message: 'Does it come with a backlit screen?'
    },\n    {
      time: 146,
      user: 'ChatBot_Alpha',
      message: 'Shame about the screen scratch, but still a beaut!'
    },\n    {
      time: 158,
      user: 'ChatBot_Beta',
      message: 'That Z80 processor was a workhorse.'
    },\n    {
      time: 170,
      user: 'ChatBot_Gamma',
      message: 'Max 56 colors seemed like a million back then!'
    },\n    {
      time: 182,
      user: 'ChatBot_Delta',
      message: 'Gotta love region-free consoles.'
    },\n    {
      time: 194,
      user: 'ChatBot_Alpha',
      message: 'Anyone else have the worm light for playing in the dark?'
    },\n    {
      time: 206,
      user: 'ChatBot_Beta',
      message: 'That startup sound is iconic.'
    },\n    {
      time: 218,
      user: 'ChatBot_Gamma',
      message: 'This would be a great addition to a retro collection.'
    },\n    {
      time: 230,
      user: 'ChatBot_Delta',
      message: 'So cool to see these still working.'
    },\n    {
      time: 242,
      user: 'ChatBot_Alpha',
      message: 'What was your first GBC game? Mine was Link\'s Awakening DX!'
    },\n    {
      time: 254,
      user: 'ChatBot_Beta',
      message: 'The see-through purple one was my favorite color.'
    },\n    {
      time: 263,
      user: 'QuestionBot',
      message: 'Does Pokemon Crystal come with the Console?'
    },\n    {
      time: 266,
      user: 'ChatBot_Gamma',
      message: 'Can almost feel those buttons now.'
    },\n    {
      time: 278,
      user: 'ChatBot_Delta',
      message: 'Hope it finds a good home!'
    },\n    {
      time: 290,
      user: 'ChatBot_Alpha',
      message: 'Retro gaming is the best.'
    },\n    {
      time: 302,
      user: 'ChatBot_Beta',
      message: 'Such a simple, perfect design.'
    },\n    {
      time: 314,
      user: 'ChatBot_Gamma',
      message: 'Good old Nintendo reliability.'
    },\n    {
      time: 328,
      user: 'ChatBot_Delta',
      message: 'The GBA SP! The red is so vibrant.'
    },\n    {
      time: 340,
      user: 'ChatBot_Alpha',
      message: 'Finally, a backlit screen! That was a game changer.'
    },\n    {
      time: 352,
      user: 'ChatBot_Beta',
      message: 'Clamshell design was genius. No more screen scratches in my pocket!'
    },\n    {
      time: 364,
      user: 'ChatBot_Gamma',
      message: 'Pokemon Ruby/Sapphire on this... hours and hours.'
    },\n    {
      time: 376,
      user: 'ChatBot_Delta',
      message: 'Loved that it was rechargeable.'
    },\n    {
      time: 388,
      user: 'ChatBot_Alpha',
      message: 'The SP felt so much more modern.'
    },\n    {
      time: 400,
      user: 'ChatBot_Beta',
      message: 'Still one of my favorite handheld designs ever.'
    },\n    {
      time: 412,
      user: 'ChatBot_Gamma',
      message: 'Advance Wars on the GBA SP was amazing.'
    },\n    {
      time: 424,
      user: 'ChatBot_Delta',
      message: 'That click when you opened and closed it was so satisfying.'
    },\n    {
      time: 436,
      user: 'ChatBot_Alpha',
      message: 'This looks like it\'s seen some adventures!'
    },\n    {
      time: 448,
      user: 'ChatBot_Beta',
      message: 'The buttons on the SP always felt good.'
    },\n    {
      time: 454,
      user: 'QuestionBot',
      message: 'Does Pokemon Ruby come with the console?'
    },\n    {
      time: 458,
      user: 'QuestionBot',
      message: 'Have there been any modifications done to the console?'
    },\n    {
      time: 460,
      user: 'ChatBot_Gamma',
      message: 'A new shell and screen and this would be mint.'
    },\n    {
      time: 461,
      user: 'QuestionBot',
      message: 'Do any accessories come with it?'
    },\n    {
      time: 472,
      user: 'ChatBot_Delta',
      message: 'So many great RPGs for the GBA.'
    },\n    {
      time: 484,
      user: 'ChatBot_Alpha',
      message: 'I miss the dedicated headphone jack sometimes, but the design was worth it.'
    },\n    {
      time: 496,
      user: 'ChatBot_Beta',
      message: 'This red is fire!'
    },\n    {
      time: 508,
      user: 'ChatBot_Gamma',
      message: 'Backward compatibility with GB/GBC games was awesome.'
    },\n    {
      time: 520,
      user: 'ChatBot_Delta',
      message: 'Golden Sun, anyone?'
    },\n    {
      time: 532,
      user: 'ChatBot_Alpha',
      message: 'The GBA SP was peak pocket gaming for me.'
    },\n    {
      time: 544,
      user: 'ChatBot_Beta',
      message: 'Small, powerful, and a great library.'
    },\n    {
      time: 545,
      user: 'QuestionBot',
      message: 'Does audio work?'
    },\n    {
      time: 556,
      user: 'ChatBot_Gamma',
      message: 'The wear and tear just adds character, haha.'
    },\n    {
      time: 562,
      user: 'CommentBot',
      message: '(No question, but people talking about being able to hear audio)'
    },\n    {
      time: 568,
      user: 'ChatBot_Delta',
      message: 'How many versions of the SP did they even make? So many colors.'
    },\n    {
      time: 580,
      user: 'ChatBot_Alpha',
      message: 'Metroid Fusion and Zero Mission were incredible on this.'
    },\n    {
      time: 592,
      user: 'ChatBot_Beta',
      message: 'Wish I still had mine.'
    },\n    {
      time: 604,
      user: 'ChatBot_Gamma',
      message: 'This is a true collector\'s item.'
    },\n    {
      time: 614,
      user: 'QuestionBot',
      message: 'Does this work with Gameboy games?'
    },\n    {
      time: 616,
      user: 'ChatBot_Delta',
      message: 'That front-lit screen was a huge step up.'
    },\n    {
      time: 628,
      user: 'ChatBot_Alpha',
      message: 'Whoever gets this is lucky!'
    },\n    {
      time: 653,
      user: 'ChatBot_Beta',
      message: 'The DSi! Getting into the dual-screen era.'
    },\n    {
      time: 665,
      user: 'ChatBot_Gamma',
      message: 'That white is super clean.'
    },\n    {
      time: 677,
      user: 'ChatBot_Delta',
      message: 'DSiWare had some fun little games.'
    },\n    {
      time: 689,
      user: 'ChatBot_Alpha',
      message: 'The cameras were a bit of a gimmick but fun for a bit!'
    },\n    {
      time: 701,
      user: 'ChatBot_Beta',
      message: 'Bigger screens than the original DS, right?'
    },\n    {
      time: 713,
      user: 'ChatBot_Gamma',
      message: 'Ah, the stylus. So many taps.'
    },\n    {
      time: 725,
      user: 'ChatBot_Delta',
      message: 'Nintendogs on the DS was a cultural phenomenon.'
    },\n    {
      time: 737,
      user: 'ChatBot_Alpha',
      message: 'Japanese consoles always have cool exclusive colors.'
    },\n    {
      time: 749,
      user: 'ChatBot_Beta',
      message: 'Region-locking for DSi specific games is a bit of a pain, but DS games are fine!'
    },\n    {
      time: 761,
      user: 'ChatBot_Gamma',
      message: 'The matte finish on some DSi models was nice.'
    },\n    {
      time: 773,
      user: 'ChatBot_Delta',
      message: 'This was when Nintendo started getting really creative with handhelds.'
    },\n    {
      time: 785,
      user: 'ChatBot_Alpha',
      message: 'Brain Age! Kept my parents busy for ages.'
    },\n    {
      time: 797,
      user: 'ChatBot_Beta',
      message: 'The click of the DS hinge is another classic sound.'
    },\n    {
      time: 809,
      user: 'ChatBot_Gamma',
      message: 'This one looks like it\'s in great shape.'
    },\n    {
      time: 821,
      user: 'ChatBot_Delta',
      message: 'The SD card slot was a welcome addition for sure.'
    },\n    {
      time: 833,
      user: 'ChatBot_Alpha',
      message: 'Still have a soft spot for the DS family.'
    },\n    {
      time: 845,
      user: 'ChatBot_Beta',
      message: 'Phantom Hourglass and Spirit Tracks! Great Zelda games.'
    },\n    {
      time: 850,
      user: 'CommentBot',
      message: '(No question, but people asking to see the screen turned on)'
    },\n    {
      time: 857,
      user: 'ChatBot_Gamma',
      message: 'The DSi browser was... an attempt!'
    },\n    {
      time: 869,
      user: 'QuestionBot',
      message: 'Can I play American DS games on this console?'
    },\n    {
      time: 869,
      user: 'ChatBot_Delta',
      message: 'PictoChat was surprisingly fun with friends.'
    },\n    {
      time: 881,
      user: 'ChatBot_Alpha',
      message: 'Sleeker than the chunky original DS.'
    },\n    {
      time: 893,
      user: 'ChatBot_Beta',
      message: 'So many great rhythm games on the DS.'
    },\n    {
      time: 905,
      user: 'ChatBot_Gamma',
      message: 'The build quality on these always felt solid.'
    },\n    {
      time: 917,
      user: 'ChatBot_Delta',
      message: 'That pristine white looks amazing.'
    },\n    {
      time: 929,
      user: 'ChatBot_Alpha',
      message: 'I wonder what\'s on that included SD card, haha (jk).'
    },\n    {
      time: 940,
      user: 'QuestionBot',
      message: 'Does this include any games?'
    },\n    {
      time: 941,
      user: 'ChatBot_Beta',
      message: 'Dual screens opened up so many new gameplay ideas.'
    },\n    {
      time: 945,
      user: 'QuestionBot',
      message: 'Does it come with any accessories?'
    },\n    {
      time: 950,
      user: 'QuestionBot',
      message: 'Does it come with a case?'
    },\n    {
      time: 953,
      user: 'ChatBot_Gamma',
      message: 'The DS had such a diverse library. Something for everyone.'
    },\n    {
      time: 965,
      user: 'ChatBot_Delta',
      message: 'Still playable today, easily.'
    },\n    {
      time: 977,
      user: 'ChatBot_Alpha',
      message: 'For DS games, this is a great find.'
    },\n    {
      time: 987,
      user: 'QuestionBot',
      message: '\"The system looks great! Any defects or other problems with the DS\"?'
    },\n    {
      time: 989,
      user: 'ChatBot_Beta',
      message: 'The speakers on the DS were pretty decent too.'
    },\n    {
      time: 995,
      user: 'QuestionBot',
      message: 'Can you test the cameras?'
    },\n    {
      time: 1001,
      user: 'ChatBot_Gamma',
      message: 'Good to know the cameras work!'
    },\n    {
      time: 1013,
      user: 'ChatBot_Delta',
      message: 'A solid piece of Nintendo history.'
    },\n    {
      time: 1025,
      user: 'ChatBot_Alpha',
      message: 'The start of the eShop era, kind of.'
    },\n    {
      time: 1037,
      user: 'ChatBot_Beta',
      message: 'Would love to play some classic DS titles on this.'
    },\n    {
      time: 1040,
      user: 'CommentBot',
      message: '(No questions, people just talking about region-bound games and the appropriate consoles. Nintendo DS and below, region free. Nintendo DSi and above, can only play that region\'s games)'
    },\n    {
      time: 1049,
      user: 'ChatBot_Gamma',
      message: 'That satisfying click when a DS game goes in.'
    },\n    {
      time: 1061,
      user: 'ChatBot_Delta',
      message: 'Hope this finds a good collector.'
    },\n    {
      time: 1079,
      user: 'ChatBot_Alpha',
      message: 'The 3DS XL! Now we\'re talking big screens!'
    },\n    {
      time: 1091,
      user: 'ChatBot_Beta',
      message: 'That Japanese \"LL\" branding is cool.'
    },\n    {
      time: 1103,
      user: 'ChatBot_Gamma',
      message: 'The 3D effect was hit or miss for me, but cool when it worked.'
    },\n    {
      time: 1115,
      user: 'ChatBot_Delta',
      message: 'StreetPass was such an innovative feature. Miss that.'
    },\n    {
      time: 1125,
      user: 'CommentBot',
      message: '(No questions, just general comments about screen size differences)'
    },\n    {
      time: 1127,
      user: 'ChatBot_Alpha',
      message: 'So many amazing games on the 3DS.'
    },\n    {
      time: 1139,
      user: 'ChatBot_Beta',
      message: 'Pokemon X/Y really showed off the system.'
    },\n    {
      time: 1151,
      user: 'ChatBot_Gamma',
      message: 'The Circle Pad was a huge improvement for 3D movement.'
    },\n    {
      time: 1155,
      user: 'QuestionBot',
      message: '\"Is the original 3ds for sale\"?'
    },\n    {
      time: 1163,
      user: 'ChatBot_Delta',
      message: 'Animal Crossing: New Leaf took over my life on the 3DS.'
    },\n    {
      time: 1175,
      user: 'ChatBot_Alpha',
      message: 'Good old eShop... RIP.'
    },\n    {
      time: 1187,
      user: 'ChatBot_Beta',
      message: 'The XL model is so much more comfortable for longer play sessions.'
    },\n    {
      time: 1199,
      user: 'ChatBot_Gamma',
      message: 'A Link Between Worlds was a masterpiece.'
    },\n    {
      time: 1211,
      user: 'ChatBot_Delta',
      message: 'Love that many Japanese 3DS games have English options. Super useful!'
    },\n    {
      time: 1223,
      user: 'ChatBot_Alpha',
      message: 'The blue one is a nice color.'
    },\n    {
      time: 1235,
      user: 'ChatBot_Beta',
      message: 'Scratches are a shame, but a new shell isn\'t too hard to find for these.'
    },\n    {
      time: 1247,
      user: 'ChatBot_Gamma',
      message: 'This is the definitive way to play 3DS games for many.'
    },\n    {
      time: 1259,
      user: 'ChatBot_Delta',
      message: 'The cameras for AR games were fun.'
    },\n    {
      time: 1260,
      user: 'QuestionBot',
      message: '\"Will there be issues between the American and Japanese chargers for the system\"? (few questions like this)'
    },\n    {
      time: 1271,
      user: 'ChatBot_Alpha',
      message: 'Still use my 3DS from time to time.'
    },\n    {
      time: 1283,
      user: 'ChatBot_Beta',
      message: 'The Virtual Console on 3DS had some gems.'
    },\n    {
      time: 1295,
      user: 'ChatBot_Gamma',
      message: 'Monster Hunter on the 3DS XL was a blast.'
    },\n    {
      time: 1300,
      user: 'QuestionBot',
      message: '\"Does the camera work\"?'
    },\n    {
      time: 1307,
      user: 'ChatBot_Delta',
      message: 'So glad it has an SD card included.'
    },\n    {
      time: 1319,
      user: 'ChatBot_Alpha',
      message: 'The sound on the 3DS XL is pretty good.'
    },\n    {
      time: 1320,
      user: 'QuestionBot',
      message: 'Volume on the system OK?'
    },\n    {
      time: 1331,
      user: 'ChatBot_Beta',
      message: 'That top screen is massive!'
    },\n    {
      time: 1343,
      user: 'ChatBot_Gamma',
      message: 'Fire Emblem Awakening, anyone?'
    },\n    {
      time: 1355,
      user: 'ChatBot_Delta',
      message: 'The wireless light is a nice touch.'
    },\n    {
      time: 1367,
      user: 'ChatBot_Alpha',
      message: 'Hope the 3D slider is still nice and firm.'
    },\n    {
      time: 1379,
      user: 'ChatBot_Beta',
      message: 'This console has so much personality.'
    },\n    {
      time: 1390,
      user: 'QuestionBot',
      message: 'Does the eShop still work and have games?'
    },\n    {
      time: 1391,
      user: 'ChatBot_Gamma',
      message: 'The game library is just incredible.'
    },\n    {
      time: 1403,
      user: 'ChatBot_Delta',
      message: 'A great system for RPG fans.'
    },\n    {
      time: 1415,
      user: 'ChatBot_Alpha',
      message: 'Kid Icarus: Uprising was underrated!'
    },\n    {
      time: 1420,
      user: 'QuestionBot',
      message: '\"Can I use my American eShop games on the Japanese console\"?'
    },\n    {
      time: 1427,
      user: 'ChatBot_Beta',
      message: 'Super Mario 3D Land was a perfect showcase for the 3D.'
    },\n    {
      time: 1430,
      user: 'QuestionBot',
      message: 'Does it come with any accessories?'
    },\n    {
      time: 1435,
      user: 'QuestionBot',
      message: '\"Does it come with any games\"?'
    },\n    {
      time: 1439,
      user: 'ChatBot_Gamma',
      message: 'I always kept the 3D slider off to save battery, lol.'
    },\n    {
      time: 1451,
      user: 'ChatBot_Delta',
      message: 'This would be great for playing Japanese exclusives.'
    },\n    {
      time: 1463,
      user: 'ChatBot_Alpha',
      message: 'The larger buttons on the XL are a plus.'
    },\n    {
      time: 1475,
      user: 'ChatBot_Beta',
      message: 'The design is quite sleek.'
    },\n    {
      time: 1487,
      user: 'ChatBot_Gamma',
      message: 'So many hours sunk into this generation.'
    },\n    {
      time: 1499,
      user: 'ChatBot_Delta',
      message: 'Good to know the charger is the same as the DSi.'
    },\n    {
      time: 1500,
      user: 'QuestionBot',
      message: 'It\'s a little bright, can you adjust the lighting to see the console better?'
    },\n    {
      time: 1511,
      user: 'ChatBot_Alpha',
      message: 'A true powerhouse of a handheld.'
    },\n    {
      time: 1523,
      user: 'ChatBot_Beta',
      message: 'The Home Menu music is so catchy.'
    },\n    {
      time: 1535,
      user: 'ChatBot_Gamma',
      message: 'Still a very capable machine.'
    },\n    {
      time: 1540,
      user: 'QuestionBot',
      message: 'Can you turn on 3d?'
    },\n    {
      time: 1547,
      user: 'ChatBot_Delta',
      message: 'Luigi\'s Mansion: Dark Moon was fantastic.'
    },\n    {
      time: 1559,
      user: 'ChatBot_Alpha',
      message: 'The stylus placement on the XL is pretty convenient.'
    },\n    {
      time: 1571,
      user: 'ChatBot_Beta',
      message: 'This will make someone very happy.'
    },\n    {
      time: 1580,
      user: 'QuestionBot',
      message: 'Is the touchpad on the bottom responsive?'
    },\n    {
      time: 1583,
      user: 'ChatBot_Gamma',
      message: 'The sheer volume of quality games is astounding.'
    },\n    {
      time: 1595,
      user: 'ChatBot_Delta',
      message: 'I like that the host is honest about the condition.'
    },\n    {
      time: 1607,
      user: 'ChatBot_Alpha',
      message: 'Even with scratches, it\'s a desirable console.'
    },\n    {
      time: 1619,
      user: 'ChatBot_Beta',
      message: 'The battery life on the XL was decent.'
    },\n    {
      time: 1631,
      user: 'ChatBot_Gamma',
      message: 'Playing DS games on this is also great with the big screens.'
    },\n    {
      time: 1635,
      user: 'QuestionBot',
      message: 'Can it play more games than just Pokemon?'
    },\n    {
      time: 1643,
      user: 'ChatBot_Delta',
      message: 'The clamshell design is just so practical for handhelds.'
    },\n    {
      time: 1655,
      user: 'ChatBot_Alpha',
      message: 'This is peak Nintendo handheld innovation for many.'
    },\n    {
      time: 1660,
      user: 'QuestionBot',
      message: 'Can you skip cutscenes 🙂?'
    },\n    {
      time: 1667,
      user: 'ChatBot_Beta',
      message: 'I should dig out my old 3DS...'
    },\n    {
      time: 1679,
      user: 'ChatBot_Gamma',
      message: 'So many memories flooding back!'
    },\n    {
      time: 1691,
      user: 'ChatBot_Delta',
      message: 'The start/select/home buttons are nicely placed.'
    },\n    {
      time: 1703,
      user: 'ChatBot_Alpha',
      message: 'The weight of the XL feels good in the hands.'
    },\n    {
      time: 1715,
      user: 'ChatBot_Beta',
      message: 'A great way to experience a massive library of games.'
    },\n    {
      time: 1727,
      user: 'ChatBot_Gamma',
      message: 'The clicky shoulder buttons are satisfying.'
    },\n    {
      time: 1730,
      user: 'QuestionBot',
      message: 'Does this come with a charger?'
    },\n    {
      time: 1739,
      user: 'ChatBot_Delta',
      message: 'This system defined a whole era of portable gaming.'
    },\n    {
      time: 1751,
      user: 'ChatBot_Alpha',
      message: 'That larger top screen makes a huge difference.'
    },\n    {
      time: 1760,
      user: 'QuestionBot',
      message: 'Can you show the condition of the 3ds again please?'
    },\n    {
      time: 1763,
      user: 'ChatBot_Beta',
      message: 'Still a popular console among collectors.'
    },\n    {
      time: 1775,
      user: 'ChatBot_Gamma',
      message: 'The matte finish on some of these was really nice.'
    },\n    {
      time: 1787,
      user: 'ChatBot_Delta',
      message: 'Hope it gets into the hands of an enthusiast!'
    },\n    {
      time: 1799,
      user: 'ChatBot_Alpha',
      message: 'The notification LED is a handy feature.'
    },\n    {
      time: 1810,
      user: 'QuestionBot',
      message: 'What\'s your favorite Pokemon gen?'
    },\n    {
      time: 1811,
      user: 'ChatBot_Beta',
      message: 'Such a robust and reliable piece of hardware.'
    },\n    {
      time: 1823,
      user: 'ChatBot_Gamma',
      message: 'Tons of great indie games on the eShop too (back in the day).'
    },\n    {
      time: 1835,
      user: 'ChatBot_Delta',
      message: 'This represents a lot of Nintendo history.'
    },\n    {
      time: 1847,
      user: 'ChatBot_Alpha',
      message: 'A fantastic find for any retro gamer.'
    },\n    {
      time: 1859,
      user: 'ChatBot_Beta',
      message: 'The 3DS family had a great run.'
    }\n  ]\n};\n