// chat2.js generated by generate_chat2.js
exports.chat = [
  {
    "timeSinceVideoStartedInMs": 41000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-01",
        "text": "Haha, a Game Boy Color... Takes me back"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 53000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-02",
        "text": "The maroon is a classic look."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 65000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-03",
        "text": "Remember trading Pokemon with the link cable? Good times!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 77000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-04",
        "text": "I wonder how many AA batteries I went through as a kid..."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 89000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-05",
        "text": "That clicky D-pad was the best."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 101000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-06",
        "text": "Pokemon Crystal on this would be epic."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 113000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-07",
        "text": "Still got my old GBC somewhere!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 125000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-08",
        "text": "The first handheld I ever owned! So many memories."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 127000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-09",
        "text": "Does the volume wheel work?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 134000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-10",
        "text": "Does it come with a backlit screen?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 137000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-11",
        "text": "Shame about the screen scratch, but still a beaut!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 149000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-12",
        "text": "That Z80 processor was a workhorse."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 161000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-13",
        "text": "Max 56 colors seemed like a million back then!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 173000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-14",
        "text": "Gotta love region-free consoles."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 185000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-15",
        "text": "Anyone else have the worm light for playing in the dark?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 197000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-16",
        "text": "That startup sound is iconic."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 209000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-17",
        "text": "This would be a great addition to a retro collection."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 221000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-18",
        "text": "So cool to see these still working."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 233000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-19",
        "text": "What was your first GBC game? Mine was Link's Awakening DX!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 245000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-20",
        "text": "The see-through purple one was my favorite color."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 254000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-21",
        "text": "Does Pokemon Crystal come with the Console?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 257000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-22",
        "text": "Can almost feel those buttons now."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 269000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-23",
        "text": "Hope it finds a good home!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 281000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-24",
        "text": "Retro gaming is the best."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 293000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-25",
        "text": "Such a simple, perfect design."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 305000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-26",
        "text": "Good old Nintendo reliability."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 319000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-27",
        "text": "The GBA SP! The red is so vibrant."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 331000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-28",
        "text": "Finally, a backlit screen! That was a game changer."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 343000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-29",
        "text": "Clamshell design was genius. No more screen scratches in my pocket!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 355000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-30",
        "text": "Pokemon Ruby/Sapphire on this... hours and hours."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 367000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-31",
        "text": "Loved that it was rechargeable."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 379000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-32",
        "text": "The SP felt so much more modern."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 391000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-33",
        "text": "Still one of my favorite handheld designs ever."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 403000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-34",
        "text": "Advance Wars on the GBA SP was amazing."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 415000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-35",
        "text": "That click when you opened and closed it was so satisfying."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 427000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-36",
        "text": "This looks like it's seen some adventures!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 439000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-37",
        "text": "The buttons on the SP always felt good."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 445000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-38",
        "text": "Does Pokemon Ruby come with the console?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 449000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-39",
        "text": "Have there been any modifications done to the console?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 451000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-40",
        "text": "A new shell and screen and this would be mint."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 452000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-01",
        "text": "Do any accessories come with it?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 463000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-02",
        "text": "So many great RPGs for the GBA."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 475000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-03",
        "text": "I miss the dedicated headphone jack sometimes, but the design was worth it."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 487000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-04",
        "text": "This red is fire!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 499000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-05",
        "text": "Backward compatibility with GB/GBC games was awesome."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 511000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-06",
        "text": "Golden Sun, anyone?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 523000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-07",
        "text": "The GBA SP was peak pocket gaming for me."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 535000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-08",
        "text": "Small, powerful, and a great library."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 536000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-09",
        "text": "Does audio work?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 547000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-10",
        "text": "The wear and tear just adds character, haha."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 553000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-11",
        "text": "I cant hear the audio!!!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 559000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-12",
        "text": "How many versions of the SP did they even make? So many colors."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 571000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-13",
        "text": "Metroid Fusion and Zero Mission were incredible on this."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 583000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-14",
        "text": "Wish I still had mine."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 595000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-15",
        "text": "This is a true collector's item."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 605000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-16",
        "text": "Does this work with Gameboy games?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 607000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-17",
        "text": "That front-lit screen was a huge step up."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 619000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-18",
        "text": "Whoever gets this is lucky!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 644000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-19",
        "text": "The DSi! Getting into the dual-screen era."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 656000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-20",
        "text": "That white is super clean."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 668000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-21",
        "text": "DSiWare had some fun little games."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 680000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-22",
        "text": "The cameras were a bit of a gimmick but fun for a bit!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 692000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-23",
        "text": "Bigger screens than the original DS, right?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 704000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-24",
        "text": "Ah, the stylus. So many taps."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 716000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-25",
        "text": "Nintendogs on the DS was a cultural phenomenon."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 728000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-26",
        "text": "Japanese consoles always have cool exclusive colors."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 740000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-27",
        "text": "Region-locking for DSi specific games is a bit of a pain, but DS games are fine!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 752000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-28",
        "text": "The matte finish on some DSi models was nice."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 764000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-29",
        "text": "This was when Nintendo started getting really creative with handhelds."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 776000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-30",
        "text": "Brain Age! Kept my parents busy for ages."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 788000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-31",
        "text": "The click of the DS hinge is another classic sound."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 800000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-32",
        "text": "This one looks like it's in great shape."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 812000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-33",
        "text": "The SD card slot was a welcome addition for sure."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 824000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-34",
        "text": "Still have a soft spot for the DS family."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 836000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-35",
        "text": "Phantom Hourglass and Spirit Tracks! Great Zelda games."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 841000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-36",
        "text": "TURN ON THE SCREEN!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 848000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-37",
        "text": "The DSi browser was... an attempt!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 860000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-38",
        "text": "Can I play American DS games on this console?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 860000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-39",
        "text": "PictoChat was surprisingly fun with friends."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 872000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-40",
        "text": "Sleeker than the chunky original DS."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 884000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-01",
        "text": "So many great rhythm games on the DS."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 896000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-02",
        "text": "The build quality on these always felt solid."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 908000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-03",
        "text": "That pristine white looks amazing."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 920000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-04",
        "text": "I wonder what's on that included SD card, haha (jk)."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 931000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-05",
        "text": "Does this include any games?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 932000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-06",
        "text": "Dual screens opened up so many new gameplay ideas."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 936000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-07",
        "text": "Does it come with any accessories?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 941000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-08",
        "text": "Does it come with a case?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 944000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-09",
        "text": "The DS had such a diverse library. Something for everyone."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 956000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-10",
        "text": "Still playable today, easily."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 968000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-11",
        "text": "For DS games, this is a great find."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 978000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-12",
        "text": "\"The system looks great! Any defects or other problems with the DS\"?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 980000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-13",
        "text": "The speakers on the DS were pretty decent too."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 986000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-14",
        "text": "Can you test the cameras?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 992000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-15",
        "text": "Good to know the cameras work!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1004000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-16",
        "text": "A solid piece of Nintendo history."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1016000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-17",
        "text": "The start of the eShop era, kind of."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1028000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-18",
        "text": "Would love to play some classic DS titles on this."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1031000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-19",
        "text": " Region-locking can be so confusing with older consoles! Good to know the details for this DSi"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1040000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-20",
        "text": "That satisfying click when a DS game goes in."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1052000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-21",
        "text": "Hope this finds a good collector."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1070000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-22",
        "text": "The 3DS XL! Now we're talking big screens!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1082000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-23",
        "text": "That Japanese \"LL\" branding is cool."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1094000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-24",
        "text": "The 3D effect was hit or miss for me, but cool when it worked."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1106000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-25",
        "text": "StreetPass was such an innovative feature. Miss that."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1116000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-26",
        "text": "WOW, Such Size difference!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1118000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-27",
        "text": "So many amazing games on the 3DS."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1130000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-28",
        "text": "Pokemon X/Y really showed off the system."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1142000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-29",
        "text": "The Circle Pad was a huge improvement for 3D movement."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1146000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-30",
        "text": "\"Is the original 3ds for sale\"?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1154000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-31",
        "text": "Animal Crossing: New Leaf took over my life on the 3DS."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1166000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-32",
        "text": "Good old eShop... RIP."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1178000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-33",
        "text": "The XL model is so much more comfortable for longer play sessions."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1190000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-34",
        "text": "A Link Between Worlds was a masterpiece."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1202000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-35",
        "text": "Love that many Japanese 3DS games have English options. Super useful!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1214000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-36",
        "text": "The blue one is a nice color."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1226000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-37",
        "text": "Scratches are a shame, but a new shell isn't too hard to find for these."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1238000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-38",
        "text": "This is the definitive way to play 3DS games for many."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1250000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-39",
        "text": "The cameras for AR games were fun."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1251000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-40",
        "text": "\"Will there be issues between the American and Japanese chargers for the system\"?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1262000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-01",
        "text": "Still use my 3DS from time to time."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1274000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-02",
        "text": "The Virtual Console on 3DS had some gems."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1286000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-03",
        "text": "Monster Hunter on the 3DS XL was a blast."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1291000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-04",
        "text": "\"Does the camera work\"?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1298000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-05",
        "text": "So glad it has an SD card included."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1310000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-06",
        "text": "The sound on the 3DS XL is pretty good."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1311000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-07",
        "text": "Volume on the system OK?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1322000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-08",
        "text": "That top screen is massive!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1334000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-09",
        "text": "Fire Emblem Awakening, anyone?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1346000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-10",
        "text": "The wireless light is a nice touch."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1358000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-11",
        "text": "Hope the 3D slider is still nice and firm."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1370000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-12",
        "text": "This console has so much personality."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1381000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-13",
        "text": "Does the eShop still work and have games?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1382000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-14",
        "text": "The game library is just incredible."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1394000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-15",
        "text": "A great system for RPG fans."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1406000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-16",
        "text": "Kid Icarus: Uprising was underrated!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1411000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-17",
        "text": "\"Can I use my American eShop games on the Japanese console\"?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1418000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-18",
        "text": "Super Mario 3D Land was a perfect showcase for the 3D."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1421000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-19",
        "text": "Does it come with any accessories?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1426000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-20",
        "text": "\"Does it come with any games\"?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1430000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-21",
        "text": "I always kept the 3D slider off to save battery, lol."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1442000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-22",
        "text": "I like Luigi."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1454000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-23",
        "text": "The larger buttons on the XL are a plus."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1466000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-24",
        "text": "The design is quite sleek."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1478000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-25",
        "text": "So many hours sunk into this generation."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1490000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-26",
        "text": "Good to know the charger is the same as the DSi."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1491000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-27",
        "text": "It's a little bright, can you adjust the lighting to see the console better?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1502000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-28",
        "text": "A true powerhouse of a handheld."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1514000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-29",
        "text": "The Home Menu music is so catchy."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1526000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-30",
        "text": "Still a very capable machine."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1531000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-31",
        "text": "Can you turn on 3d?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1538000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-32",
        "text": "Luigi's Mansion: Dark Moon was fantastic."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1550000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-33",
        "text": "The stylus placement on the XL is pretty convenient."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1562000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-34",
        "text": "This will make someone very happy."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1571000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-35",
        "text": "Is the touchpad on the bottom responsive?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1574000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-36",
        "text": "The sheer volume of quality games is astounding."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1586000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-37",
        "text": "I like that the host is honest about the condition."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1598000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-38",
        "text": "Even with scratches, it's a desirable console."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1610000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-39",
        "text": "The battery life on the XL was decent."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1622000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-40",
        "text": "Playing DS games on this is also great with the big screens."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1626000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-01",
        "text": "Can it play more games than just Pokemon?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1634000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-02",
        "text": "The clamshell design is just so practical for handhelds."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1646000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-03",
        "text": "This is peak Nintendo handheld innovation for many."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1651000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-04",
        "text": "Can you skip cutscenes 🙂?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1658000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-05",
        "text": "I should dig out my old 3DS..."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1670000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-06",
        "text": "So many memories flooding back!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1682000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-07",
        "text": "The start/select/home buttons are nicely placed."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1694000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-08",
        "text": "The weight of the XL feels good in the hands."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1706000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-09",
        "text": "A great way to experience a massive library of games."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1718000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-10",
        "text": "The clicky shoulder buttons are satisfying."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1721000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-11",
        "text": "Does this come with a charger?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1730000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-12",
        "text": "This system defined a whole era of portable gaming."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1742000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-13",
        "text": "That larger top screen makes a huge difference."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1751000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-14",
        "text": "Can you show the condition of the 3ds again please?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1754000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-15",
        "text": "Still a popular console among collectors."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1766000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-16",
        "text": "The matte finish on some of these was really nice."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1778000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-17",
        "text": "Hope it gets into the hands of an enthusiast!"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1790000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-18",
        "text": "The notification LED is a handy feature."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1801000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-19",
        "text": "What's your favorite Pokemon gen?"
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1802000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-20",
        "text": "Such a robust and reliable piece of hardware."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1814000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-21",
        "text": "Tons of great indie games on the eShop too (back in the day)."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1826000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-22",
        "text": "This represents a lot of Nintendo history."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1838000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-23",
        "text": "A fantastic find for any retro gamer."
      }
    }
  },
  {
    "timeSinceVideoStartedInMs": 1850000,
    "persistInHistory": false,
    "action": {
      "channel": "game.chat",
      "data": {
        "user": "bot-24",
        "text": "The 3DS family had a great run."
      }
    }
  }
];
