// generate_chat2.js
// Standalone script to generate chat2.js from chat.js with adjusted timings
const fs = require('fs');
const path = require('path');

// Load the original chat array
const chatPath = path.join(__dirname, 'chat.js');
const chat = require(chatPath).chat;

const newChat = chat.map(entry => {
  const newEntry = JSON.parse(JSON.stringify(entry));
  if (typeof newEntry.timeSinceVideoStartedInMs === 'number') {
    newEntry.timeSinceVideoStartedInMs = Math.max(0, newEntry.timeSinceVideoStartedInMs - 3000);
  }
  return newEntry;
});

const output = `// chat2.js generated by generate_chat2.js\nexports.chat = ${JSON.stringify(newChat, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, 'chat2.js'), output);

console.log('chat2.js has been created with timeSinceVideoStartedInMs adjusted by -2000ms.'); 