// generate_commentary2.js
// Standalone script to generate commentary2.js from commentary.js with adjusted timings
const fs = require('fs');
const path = require('path');

// Load the original commentary array
const commentaryPath = path.join(__dirname, 'commentary.js');
const commentary = require(commentaryPath).commentary;

function subtractSeconds(timeCode, seconds) {
  // timeCode format: 'MM:SS' or 'H:MM:SS'
  const parts = timeCode.split(':').map(Number);
  let totalSeconds = 0;
  if (parts.length === 2) {
    totalSeconds = parts[0] * 60 + parts[1];
  } else if (parts.length === 3) {
    totalSeconds = parts[0] * 3600 + parts[1] * 60 + parts[2];
  }
  totalSeconds -= seconds;
  if (totalSeconds < 0) totalSeconds = 0;
  // Convert back to MM:SS or H:MM:SS
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.floor((totalSeconds % 3600) / 60);
  const s = totalSeconds % 60;
  if (h > 0) {
    return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  } else {
    return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  }
}

const newCommentary = commentary.map(entry => {
  const newEntry = JSON.parse(JSON.stringify(entry));
  if (typeof newEntry.timeSinceVideoStartedInMs === 'number') {
    newEntry.timeSinceVideoStartedInMs = Math.max(0, newEntry.timeSinceVideoStartedInMs - 4000);
  }
  if (newEntry.action && newEntry.action.data && newEntry.action.data.timeCode) {
    newEntry.action.data.timeCode = subtractSeconds(newEntry.action.data.timeCode, 4);
  }
  return newEntry;
});

const output = `// commentary2.js generated by generate_commentary2.js\nexports.commentary = ${JSON.stringify(newCommentary, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, 'commentary2.js'), output);

console.log('commentary2.js has been created with timeCodes adjusted by -4 seconds and timeSinceVideoStartedInMs by -4000ms.'); 