// Generated by generate_reactions_js.py
// Contains timed and random reactions for the live shopping experience.

exports.reactions = [
  {
    timeSinceVideoStartedInMs: 2519,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 24160,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 41139,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 50395,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 12,
  },
  {
    timeSinceVideoStartedInMs: 50395,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 50395,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 15,
  },
  {
    timeSinceVideoStartedInMs: 70000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 70000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 74359,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 74900,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 75000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 111015,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 134939,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 147633,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 154201,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 170727,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 179641,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 180363,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 183819,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 191206,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 200258,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 206705,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 210958,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 228448,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 242807,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 260313,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 272327,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 277966,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 298347,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 298719,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 302001,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 306017,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 307096,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 307612,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 325870,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 328835,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 328835,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💎`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 328835,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 331748,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 333804,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 340000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💎`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 340000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😡`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 375113,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 391501,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 399806,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 425628,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 440888,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 441291,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 450000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 450000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 3,
  },
  {
    timeSinceVideoStartedInMs: 459370,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 483055,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 492981,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 499725,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 570470,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 572446,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 601319,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 628775,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 653035,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 12,
  },
  {
    timeSinceVideoStartedInMs: 653035,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 653035,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 12,
  },
  {
    timeSinceVideoStartedInMs: 663737,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 665000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 12,
  },
  {
    timeSinceVideoStartedInMs: 665000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 665000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 665373,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 667147,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 672102,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 700976,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 702688,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 715511,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 730272,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 742473,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 750000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 750000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😡`, type: "reaction" },
    },
    repeat: 3,
  },
  {
    timeSinceVideoStartedInMs: 751146,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 759172,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 763113,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 765000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 765000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 3,
  },
  {
    timeSinceVideoStartedInMs: 769895,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 796622,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 823777,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 843430,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 856012,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 883243,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 892069,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 901132,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 908190,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 911208,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 936821,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 956206,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 961977,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 997648,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1033567,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1057878,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1079565,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 12,
  },
  {
    timeSinceVideoStartedInMs: 1079565,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 1079565,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 15,
  },
  {
    timeSinceVideoStartedInMs: 1080641,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1088659,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1095000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 1095000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😡`, type: "reaction" },
    },
    repeat: 3,
  },
  {
    timeSinceVideoStartedInMs: 1139603,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1145168,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1146212,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1152093,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1152469,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1156489,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1165721,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1170000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 1170000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 1170000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 1174866,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1192132,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1200000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 1200000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 1200000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 6,
  },
  {
    timeSinceVideoStartedInMs: 1206332,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1210474,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1219741,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1233360,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1235054,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1255546,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1283751,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1298367,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1308810,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1331657,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1358408,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1369167,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1373944,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1409935,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1427436,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1456989,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1465518,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1465752,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1475677,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1493974,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1497515,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1499149,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1518828,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1526478,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1539567,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1555369,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1559745,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1565687,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1604869,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1604900,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1609664,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1616015,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1645827,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1646501,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1649010,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1655091,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1666859,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1668710,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1671401,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1675161,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1688037,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1709854,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1731594,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1739784,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1763435,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1785918,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1797735,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1806526,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1808915,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1808939,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1821867,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1827617,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1830049,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1831641,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1840595,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1841255,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1841377,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1849639,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1860000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `😮`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 1860000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 12,
  },
  {
    timeSinceVideoStartedInMs: 1860000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 1866028,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1876765,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 18,
  },
  {
    timeSinceVideoStartedInMs: 1876765,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🔥`, type: "reaction" },
    },
    repeat: 12,
  },
  {
    timeSinceVideoStartedInMs: 1876765,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 1877351,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 1,
  },
  {
    timeSinceVideoStartedInMs: 1891263,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1897075,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1937567,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1950000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 15,
  },
  {
    timeSinceVideoStartedInMs: 1950000,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 9,
  },
  {
    timeSinceVideoStartedInMs: 1953825,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `💸`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1966829,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `🎉`, type: "reaction" },
    },
    repeat: 2,
  },
  {
    timeSinceVideoStartedInMs: 1973220,
    persistInHistory: false,
    action: {
      channel: "game.stream-reactions",
      data: { text: `👏`, type: "reaction" },
    },
    repeat: 2,
  }
];
