import type { WalkthroughStep } from './types'

export const pubnubSteps: WalkthroughStep[] = [
  {
    id: 'pn-chat',
    targetSelector: '[data-walkthrough-id="chat-messages"]',
    title: 'Real-Time Chat',
    body: 'Chat is powered by the **PubNub Chat SDK**. Messages are delivered to all connected viewers in under 50ms via Pub/Sub. The `channel.connect()` callback fires for every new message — no polling, no WebSocket boilerplate.',
    placement: 'right',
    mode: 'pubnub',
    order: 1,
  },
  {
    id: 'pn-presence',
    targetSelector: '[data-walkthrough-id="viewer-count"]',
    title: 'Live Viewer Count',
    body: 'PubNub **Presence** tracks viewer occupancy in real-time. `hereNow()` returns the current count, and `onPresence` events fire instantly on join/leave. No separate analytics service needed.',
    placement: 'bottom',
    mode: 'pubnub',
    order: 2,
  },
  {
    id: 'pn-reactions',
    targetSelector: '[data-walkthrough-id="emoji-reactions"]',
    title: 'Emoji Reactions',
    body: 'Reactions flow through a dedicated PubNub channel (`stream.reactions`). Each emoji is a lightweight `publish()` call — every viewer sees the floating animation simultaneously. Rate-limited client-side to prevent spam.',
    placement: 'top',
    mode: 'pubnub',
    order: 3,
  },
  {
    id: 'pn-commentary',
    targetSelector: '[data-walkthrough-id="commentary"]',
    title: 'Live Commentary Feed',
    body: 'Commentary runs on its own channel (`game.commentary`). The backend script publishes timestamped updates that all clients receive instantly. Separate channels keep concerns isolated — chat, commentary, and control events never interfere.',
    placement: 'left',
    mode: 'pubnub',
    order: 4,
  },
  {
    id: 'pn-products',
    targetSelector: '[data-walkthrough-id="product-card"]',
    title: 'Product Highlights',
    body: 'Products appear via `PRODUCT_HIGHLIGHT` messages on `game.product-highlight`. The backend publishes product data and all clients render the card **simultaneously**. `PRODUCT_DISMISS` hides it — perfect for time-limited flash sales.',
    placement: 'left',
    mode: 'pubnub',
    prepareUI: 'showProduct',
    order: 5,
  },
  {
    id: 'pn-betting',
    targetSelector: '[data-walkthrough-id="bet-card"]',
    title: 'In-Play Betting',
    body: 'Bet proposals arrive via a dedicated channel with question, options, and odds. Results are published when the bet resolves — the client compares the selected option to determine win/loss and triggers coin animations.',
    placement: 'left',
    mode: 'pubnub',
    order: 6,
  },
  {
    id: 'pn-wallet',
    targetSelector: '[data-walkthrough-id="coin-wallet"]',
    title: 'Virtual Coin Economy',
    body: 'The wallet state is managed locally and updated via PubNub events. Winnings are calculated client-side from bet odds. The `useWallet` hook triggers bounce animations on balance changes — all reactive, all real-time.',
    placement: 'bottom',
    mode: 'pubnub',
    order: 7,
  },
  {
    id: 'pn-video-sync',
    targetSelector: '',
    title: 'Video Sync Control',
    body: 'The backend publishes `STATUS` and `SEEK` messages on `game.video-control` to synchronize video playback across all clients. Late joiners receive the current playback time and seek to the right position automatically.',
    placement: 'center',
    mode: 'pubnub',
    order: 8,
  },
  {
    id: 'pn-summary',
    targetSelector: '',
    title: 'PubNub Architecture',
    body: '**Pub/Sub** for chat + reactions + betting, **Presence** for live viewer count, **Chat SDK** for message history and user management, **multiple channels** for isolated concerns. All real-time, all managed — zero infrastructure to operate.',
    placement: 'center',
    mode: 'pubnub',
    order: 9,
  },
]
